name: Release Artifact

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-test-lint-upload:
    name: Build, Test, Lint, and Upload Release Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Clean Go module and build cache
        run: |
          go clean -modcache
          go clean -cache

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          only-new-issues: false

      - name: Lint
        run: golangci-lint run

      - name: Run tests
        run: go test -v ./...

      - name: Build binary
        run: |
          EXT=""
          if [ "${{ matrix.os }}" = "windows" ]; then EXT=".exe"; fi
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o chezmoi-a-la-carte-${{ matrix.os }}-${{ matrix.arch }}$EXT ./cmd/chezmoi-a-la-carte

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: chezmoi-a-la-carte-${{ matrix.os }}-${{ matrix.arch }}*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
